GET http://localhost:8080/main?num1=45&num2=22&operation=multiply

###
POST http://localhost:8080/reg?name=Andrei&login=Andrew&password=12345

###
POST http://localhost:8080/reg?name=Bob&login=Bob1&password=12345

###
POST http://localhost:8080/auth?login=Bob1&password=12345

###
POST http://localhost:8080/auth?login=A1ndrew&password=12345

###
GET http://localhost:8080/logout

###